project_id = "rsffywjnbzspbwlyldup"

[functions.initialize-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.purchase-data]
verify_jwt = false

[functions.request-withdrawal]
verify_jwt = false

[functions.send-sms]
verify_jwt = false
